name: Freeze.org
favicon: null
layout_spectrum: 0.8872496108524501
typography_spectrum: 0.6771704067941755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030301'
    - '#ffffff'
    - '#4f3417'
    - '#868583'
    - '#00a8ab'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
